name: Deno Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run Deno Format Check
        run: deno fmt --check

      - name: Run Deno Lint
        run: deno lint

      - name: Run Deno tests
        run: deno test --allow-read --coverage=cov/

      - name: Generate LCOV report
        run: deno coverage --lcov cov/ > cov.lcov
